# One-off reconnaissance helper for the docs import (tools/import-docs.mjs).
#
# Why: the reference documentation (docs.pilot-gps.africa) is generated by
# Dr.Explain. Every page renders its body inside
# <div id="hiddenContent"> > <article> > <div class="description_on_page">.
# This script downloads one page and prints that region (or writes it to a file)
# so the importer's block converter can be written against real markup.
#
# Usage:
#   powershell -File tools/docs-recon.ps1 -Url https://docs.pilot-gps.africa/map_tools.html
#   powershell -File tools/docs-recon.ps1 -Url ... -Out $env:TEMP\map_tools.content.html -Full

param(
    [Parameter(Mandatory = $true)]
    [string]$Url,

    [string]$Out,

    # Print/write the whole <div class="description_on_page"> region instead of
    # a trimmed preview.
    [switch]$Full
)

$html = (Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 60).Content

$start = $html.IndexOf('class="description_on_page"')
if ($start -lt 0) {
    throw "No content region found at $Url"
}

# Start at the opening tag of the wrapper div itself, not at its class attribute.
$start = $html.LastIndexOf('<div', $start)

# Walk forward to the matching close of the wrapper div by counting div tags.
$region = $html.Substring($start)
$depth = 0
$end = -1
foreach ($m in [regex]::Matches($region, '<div\b|</div>')) {
    if ($m.Value -eq '<div') { $depth++ } else { $depth-- }
    if ($depth -eq 0) { $end = $m.Index + $m.Length; break }
}
$region = $region.Substring(0, $end)

if ($Out) {
    $region | Out-File -Encoding utf8 $Out
    "Wrote $Out ($($region.Length) chars)"
}
elseif ($Full) {
    $region
}
else {
    $region.Substring(0, [Math]::Min(4000, $region.Length))
}
